name: Hugo Preview to an Nginx Docker

on:
  workflow_call:
    secrets:
      WG_CLIENT_PRIVATEKEY: 
        required: true
      SSH_KEY: 
        required: true

#Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  hugo-preview-nginx-docker:
    name: "Hugo Preview to an Nginx Docker"
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Start deployment
        uses: bobheadxi/deployments@v0.6.0
        id: deployment
        with:
          step: start
          token: ${{ github.token }}
          env: pr-${{ github.event.number }}
          ref: ${{ github.head_ref }}
          no_override: false

      # Setup Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: '0.115.0'
          extended: true

      # Build Hugo Website
      - name: Build website with Hugo
        run: hugo --minify --baseURL "https://preview.atletiekregels.nl/${{ github.event.number }}"

      # Wireguard - Install
      - name: Wireguard - Install
        run: sudo apt install wireguard wireguard-tools

      # Wireguard - Setup
      - name: Wireguard - Setup
        run: | 
          echo "${{ secrets.WG_CLIENT_PRIVATEKEY }}" > privatekey
          sudo ip link add dev wg0 type wireguard
          sudo ip address add dev wg0 ${{ vars.WG_CLIENT_IP }}
          sudo wg set wg0 listen-port 48123 private-key privatekey peer ${{ vars.SHARED_WG_SERVER_PUBLICKEY }} allowed-ips ${{ vars.SHARED_WG_SERVER_IPSPACE }} endpoint ${{ vars.SHARED_WG_SERVER_ENDPOINT }}
          sudo ip link set up dev wg0
          sudo ip route add ${{ vars.SHARED_WG_SERVER_IPSPACE }} dev wg0
    
      # Deploy build website with rsync to host
      - name: Deploy website with rsync
        uses: Burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --quiet --delete
          path: public/
          remote_path: "${{ vars.SSH_PREVIEW_PATH }}/${{ github.event.number }}"
          remote_host: ${{ vars.SSH_HOST }}
          remote_user: ${{ vars.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}

      - name: Finish deployment
        uses: bobheadxi/deployments@v0.6.0
        if: always()
        with:
          step: finish
          token: ${{ github.token }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: "https://preview.atletiekregels.nl/${{ github.event.number }}/"
          no_override: true
          auto_inactive: false

      - name: Find PR comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          comment-author: 'github-actions[bot]'
          body-includes: "preview of this pull request"
  
      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.number }}
          body: |
            A preview of this pull request is ready!
            See it at https://preview.atletiekregels.nl/${{ github.event.number }}/
          edit-mode: replace