name: Greeting on variable day

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
    secrets:
      TEST: 
        required: true
          
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: "Say Hello Mona it's Monday"
        run: |
          echo "dit is een ${{ vars.TESTJE}} !"
          echo "dit is 2e ${{ vars.TEST789}} !"
          echo "dit is 2e ${{ vars.DG}} !"
          echo "dit is een secret ${{ secrets.TEST}} !"

      - name: "Say DG!"
        run: echo "dit is 2e ${{ vars.DG}} !"