name: Greeting on variable day

on:
  workflow_dispatch

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "dit is een ${{ vars.TESTJE}} . !"