name: tf-apply

on:
  workflow_call:
    secrets:
      TF_VAR_cloudflare_api_token: 
        required: false
      TF_VAR_github_owner: 
        required: false
      TF_VAR_github_token: 
        required: false
      TF_VAR_ovh_app_key: 
        required: false
      TF_VAR_ovh_app_secret: 
        required: false
      TF_VAR_ovh_consumer_key: 
        required: false

#Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: write
  pull-requests: write

#These environment variables are used by the terraform azure provider to setup OIDD authenticate. 
env:
  ARM_CLIENT_ID: "${{ vars.SHARED_AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ vars.SHARED_AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ vars.SHARED_AZURE_TENANT_ID }}"
  TF_VAR_cloudflare_api_token : ${{ secrets.TF_VAR_cloudflare_api_token }}
  TF_VAR_github_owner : ${{ secrets.TF_VAR_github_owner }}
  TF_VAR_github_token : ${{ secrets.TF_VAR_github_token }}
  TF_VAR_ovh_app_key : ${{ secrets.TF_VAR_ovh_app_key }}
  TF_VAR_ovh_app_secret : ${{ secrets.TF_VAR_ovh_app_secret }}
  TF_VAR_ovh_consumer_key : ${{ secrets.TF_VAR_ovh_consumer_key }}
   
jobs:
  apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4.1.7

      # Terraform Setup
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3.1.2

      # Login to Azure CLI
      - name: 'Az CLI login'
        uses: Azure/login@v2
        with:
            client-id: ${{ vars.SHARED_AZURE_CLIENT_ID }}
            tenant-id: ${{ vars.SHARED_AZURE_TENANT_ID }}
            subscription-id: ${{ vars.SHARED_AZURE_SUBSCRIPTION_ID }}

      # Terraform Init
      - name: Terraform Init
        run: terraform init

      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve

      # NTFY Message (https://ntfy.durand.guru/docs/examples/?h=git#github-actions) (https://docs.github.com/en/actions/learn-github-actions/contexts)
      - name: NTFY
        if: always()
        run: |
          curl \
          -H "Title: ${{ github.workflow }} has status ${{ job.status}}" \
          -H "Content-Type: text/plain" \
          -d $'Repo: ${{ github.repository }}\nCommit: ${{ github.event.head_commit.message }}\nBy: ${{ github.actor }}\nStatus: ${{ job.status}}' \
          ${{ vars.NTFY_URL }}